# -*- coding: utf-8 -*-
#Pentagon numbers
#Problem 44 
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first
#ten pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
#70 − 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
#difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
import math

def ispen(x):
    n1=(1.0+math.sqrt(1.0+(24.0*x)))/6.0
    n2=(1.0-math.sqrt(1.0+(24.0*x)))/6.0
    if (n1>0 and n1.is_integer()) or (n2>0 and n2.isInteger()):
        return True
    else:
        return False




t=1
l=0
set=set()
k=0

while k==0:
    for n in range(t,t+100):
        set.add(float(n*((3*n)-1)/2))
        
        
   
    for pj in set:
        for pk in set:
            if (ispen(abs(pj-pk))):
            
                if ispen(abs(pj+pk)):
                    l=pk-pj
                    k=1
                    print pj,pk
                    print "DONE !11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
                    print "DONE !11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
                    print "DONE !11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
                   

                    

    t+=100
    print "OK"

                    
print abs(l)  
    
    
